# Generated by Django 3.2.23 on 2024-02-05 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_voetbalspelers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voetbalspelers',
            old_name='current_club',
            new_name='huidige_club',
        ),
    ]
