# Generated by Django 3.2.23 on 2024-02-05 13:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_dureparadepaardjes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dureparadepaardjes',
            new_name='Dureparadepaardje',
        ),
    ]
