# Generated by Django 3.2.23 on 2024-02-17 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_wielrenner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voetbalspeler',
            old_name='huidige_club',
            new_name='huidigeclub',
        ),
        migrations.RenameField(
            model_name='voetbalspeler',
            old_name='naam_speler',
            new_name='naamspeler',
        ),
        migrations.RenameField(
            model_name='wielrenner',
            old_name='naam_renner',
            new_name='naamrenner',
        ),
    ]
