# Generated by Django 3.2.23 on 2024-02-25 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20240217_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wielrenner',
            name='author',
        ),
        migrations.DeleteModel(
            name='Voetbalspeler',
        ),
        migrations.DeleteModel(
            name='Wielrenner',
        ),
    ]
